site_name: CIM Modeling Guide
repo_url: https://github.com/CIMug-org/cim-modeling-guide
theme:
  name: material
  features:
    - content.code.copy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
nav:
  - 'index.md'
  - 'section1-artifacts-under-cim-management.md'
  - 'section2-artifacts-under-cim-management.md'
  - 'section3-definitions.md'
  - 'section4-cim-overview.md'
  - 'section5-cim-uml-modeling-rules-and-recommendations.md'
  - 'section6-cim-uml-extension-rules-and-recommendations.md'
  - 'section7-cim-uml-transformation-rules-and-recommendations.md'
  - 'section8-cim-uml-version-control-rules.md'
  - 'section9-artifacts-under-cim-management.md'
  - 'section10-cim-management-tools.md'
  - 'Section 1 - Introduction':
    - 'section1/create-a-project.md'
    - 'section1/navigate-workspace.md'
  - 'Section 2 - References':
    - 'section2/create-a-project.md'
    - 'section2/navigate-workspace.md'
  - 'Section 3 - Definitions':
    - 'section3/create-a-project.md'
    - 'section3/navigate-workspace.md'
  - 'Section 4 - CIM Overview':
    - 'section4/create-a-project.md'
    - 'section4/navigate-workspace.md'
  - 'Section 5 - CIM UML Modeling Rules and Recommendations':
    - 'section5/create-a-project.md'
    - 'section5/navigate-workspace.md'
  - 'Section 6 - CIM UML Extension Rules and Recommendations':
    - 'section6/create-a-project.md'
    - 'section6/navigate-workspace.md'
  - 'Section 7 - CIM UML Transformation Rules and Recommendations':
    - 'section7/create-a-project.md'
    - 'section7/navigate-workspace.md'
  - 'Section 8 - CIM UML Version Control Rules':
    - 'section8/create-a-project.md'
    - 'section8/navigate-workspace.md'
  - 'Section 9 - Artifacts Under CIM Management':
    - 'section9/create-a-project.md'
    - 'section9/navigate-workspace.md'
  - 'Section 10 - CIM Management Tools':
    - 'section10/create-a-project.md'
    - 'section10/navigate-workspace.md'
