site_name: CIM Modeling Guide
repo_url: https://github.com/CIMug-org/cim-modeling-guide
theme:
  palette:
    primary: white
  logo: images/media/logo-gray.png
  name: material
  features:
    - content.code.copy
    - navigation.footer
copyright: Copyright &copy; 2019 - 2023. All rights reserved by the UCA International CIM Users Group
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - footnotes
  - admonition
  - tables
  - pymdownx.details
plugins:
  - search
  - with-pdf:
      copyright:   Version 1.1, © November 2021. All rights reserved by the UCA International Users Group
      cover: true
      cover_title: CIM Modeling Guide
      cover_subtitle: Version 1.1, © November 2021
      toc_title: Table of Contents
      heading_shift: true
      toc_level: 3
      show_anchors: true
  # This 'mike' plugin is for publishing multiple versions see https://github.com/jimporter/mike
  - mike: 
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
extra:
  version:
    provider: mike
nav:
  - 'index.md'
  - 'section1-introduction.md'
  - 'section2-references.md'
  - 'section3-definitions.md'
  - 'section4-cim-overview.md'
  - 'section5-cim-uml-modeling-rules-and-recommendations.md'
  - 'section6-cim-uml-extension-rules-and-recommendations.md'
  - 'section7-cim-uml-transformation-rules-and-recommendations.md'
  - 'section8-cim-uml-version-control-rules.md'
  - 'section9-artifacts-under-cim-management.md'
  - 'section10-cim-management-tools.md'
