site_name: CIM Modeling Guide
repo_url: https://github.com/CIMug-org/cim-modeling-guide
theme:
  palette:
    primary: white
  logo: images/media/logo-gray.png
  favicon: images/media/logo-white.png
  name: material
  features:
    - content.code.copy
    - navigation.footer
copyright: Copyright &copy; 2019 - 2024. All rights reserved by the UCA International CIM Users Group
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - footnotes
  - admonition
  - tables
  - pymdownx.details
plugins:
  - search
  - enumerate-headings:
      toc_depth: 6
      exclude:
        - index.md
  - with-pdf:
      author: UCA International Users Group
      copyright: © Copyright 2021, UCA International Users Group, All rights reserved
      cover: true
      cover_title: CIM Modeling Guide
      cover_subtitle: Version 1.1,  13-February-2021
      toc_title: Table of Contents
      heading_shift: true
      ordered_chapter_level: 0
      toc_level: 3
      show_anchors: true
      enabled_if_env: ENABLE_PDF_EXPORT
      output_path: pdf/CIM_Modeling_Guide.pdf
  # This 'mike' plugin is for publishing multiple versions see https://github.com/jimporter/mike
  - mike: 
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
extra:
  version:
    provider: mike
nav:
  - 'index.md'
  - 'revision-history.md'
  - '1. Introduction': 'section1-introduction.md'
  - '2. References': 'section2-references.md'
  - '3. Definitions': 'section3-definitions.md'
  - '4. CIM Overview': 'section4-cim-overview.md'
  - '5. CIM UML Modeling Rules and Recommendations': 'section5-cim-uml-modeling-rules-and-recommendations.md'
  - '6. CIM UML Extension Rules and Recommendations': 'section6-cim-uml-extension-rules-and-recommendations.md'
  - '7. CIM UML Transformation Rules and Recommendations': 'section7-cim-uml-transformation-rules-and-recommendations.md'
  - '8. CIM UML Version Control Rules': 'section8-cim-uml-version-control-rules.md'
  - '9. Artifacts Under CIM Management': 'section9-artifacts-under-cim-management.md'
  - '10. CIM Management Tools': 'section10-cim-management-tools.md'