site_name: CIM Modeling Guide
repo_url: https://github.com/CIMug-org/cim-modeling-guide
theme:
  palette:
    primary: white
  logo: images/media/logo-gray.png
  name: material
  features:
    - content.code.copy
    - navigation.footer
copyright: Copyright &copy; 2019 - 2023. All rights reserved by the UCA International CIM Users Group
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - footnotes
  - admonition
  - tables
  - pymdownx.details
plugins:
  - search
  - with-pdf:
      copyright: CIMug Users Group
      cover: true
      cover_title: CIM Users Group
      cover_subtitle: CIM Modeling Guide
      toc_title: Table of Contents
      heading_shift: true
      toc_level: 3
      show_anchors: true
nav:
  - 'index.md'
  - 'section1-introduction.md'
  - 'section2-references.md'
  - 'section3-definitions.md'
  - 'section4-cim-overview.md'
  - 'section5-cim-uml-modeling-rules-and-recommendations.md'
  - 'section6-cim-uml-extension-rules-and-recommendations.md'
  - 'section7-cim-uml-transformation-rules-and-recommendations.md'
  - 'section8-cim-uml-version-control-rules.md'
  - 'section9-artifacts-under-cim-management.md'
  - 'section10-cim-management-tools.md'
