name: Generate CIM Modeling Guide PDF
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4
    - name: Install/setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install mkdocs documentation tool and plugins
      run: pip install -r requirements.txt
    - name: Build the documentation including PDF
      run: mkdocs build
      env:
        ENABLE_PDF_EXPORT: 1
    - name: Upload CIM Modeling Guide PDF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: CIM_Modeling_Guide.pdf
        path: site/pdf/CIM_Modeling_Guide.pdf