name: Generate CIM Modeling Guide PDF
on:
  release:
    types: [published]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2
    - name: Install/setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install mkdocs documentation tool
      run: pip install mkdocs-material
    - name: Install PDF export plugin dependency (Pango)
      run: sudo apt install libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0
    - name: Install PDF export plugin for mkdocs
      run: pip install mkdocs-pdf-export-plugin
    - name: Build the documentation including PDF
      run: mkdocs build
      env:
        ENABLE_PDF_EXPORT: 1
    - name: Upload CIM Modeling Guide PDF as artifact
      uses: actions/upload-artifact@v3
      with:
        name: CIM Modeling Guide.pdf
        path: site/CIM_Modeling_Guide.pdf